#spring-boot-starter-jdbc application config
#
spring:
  name: Local-yaml
  main:
    banner-mode: off
  jpa:
  #    hibernate-ddl-auto: update
  #    generate-ddl: true
  #    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://127.0.0.1:5432/postgresql'
    username: 'postgresql'
    password: 'postgresql'
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5


